### ISSUE TITLE
Hermès X Prométhée - Améliorations Ergo

### ISSUE THREAD

**Issue by alexisrousseau** [lespoupeesrusses/promethee#11]
- [ ] Manque une fenêtre de confirmation lorsqu'on actualise/exit sans sauvegarder
- [ ] Clic on the image to change : ne fonctionne pas
![capture d ecran 2018-01-23 a 14 49 39](https://user-images.githubusercontent.com/25788857/35279261-d6e2e5e8-004c-11e8-84a7-9daa4a94471b.png)
- [ ] Affichage des styles de font du front directement dans l'editeur
- [ ] Éditeur de texte, changer le raccourci clavier de centrage du contenu (cmd + shift + E) en (cmd + shift + C)
- [ ] Lorsque l'on est en mode "dragable", on ne voit pas l'élément que l'on drag (ici le composant cover est rempli avec une image et du texte)
![capture d ecran 2018-01-23 a 14 55 05](https://user-images.githubusercontent.com/25788857/35279506-8c64f51e-004d-11e8-8260-464d03d87150.png)
- [ ] Supprimer le style lors d'un copié collé
- [ ] En mode "dragable" il n'y a pas l'apercu des offset, ni du font-style, prends pas en compte les offsets
- [ ] En mode preview, les font sont boldés
- [ ] Ne pas donner la possibilité de mettre une cover dans une colonne

**Comment by arnaudlevy** [comment]
OSEF
