### ISSUE TITLE
Page "La Plage" Hermès

### ISSUE THREAD

**Issue by pabois** [lespoupeesrusses/promethee#12]
- [x] Lock l'éditeur en full screen
- [x] Ajouter le btn save en full screen
- [x] Gérer container fluide
- [x] Gérer les marges après la paragraphes
- [x] Gérer les marges après les images
- [x] Gérer les marges après les rows
- [x] Gérer les marges après les vidéos
- [x] Annuler les marges qui se suivent
- [x] Gérer la vidéo à la racine (en css)
- [ ] Ajouter un composant générique "aside"
- [ ] Ajout un composant spécifique Hermès "synthèse"
- [ ] Couleurs de textes sombre/clair dans les cover (case à cocher)
- [x] Gérer les cas de background du row (on peut faire pour le moment un background oui/non, la totale c'est background-color, background-image, background-video, background-fixed/center)
- [ ] Filtre html dans summernote
- [ ] Gestion des sliders (à renommer Collection)
- [ ] Gestion des liens

**Comment by juliendargelos** [comment]
ba176ba95331757e9a0a60e0798e0764eaacc0d5

**Comment by juliendargelos** [comment]
3c9b62586e5385ec113a32555b97f1ffd935ae4f

**Comment by juliendargelos** [comment]
[4d6b17e](https://github.com/lespoupeesrusses/hermes/commit/4d6b17eb22bdb90bafc43f59e2874e0021ccb5be) Root rows behaves like container
