### ISSUE TITLE
Cover : Utiliser le gyroscope pour déplacer dans l'image

### ISSUE THREAD

**Issue by pabois** [lespoupeesrusses/promethee#23]

**Comment by arnaudlevy** [comment]
https://github.com/tregoning/photoTilt

**Comment by arnaudlevy** [comment]
On laisse tomber, Apple va bloquer le gyro pour Safari.
https://www.cultofmac.com/604562/apple-plans-to-limit-accelerometer-and-gyroscope-access-in-safari-on-ios/
