### ISSUE TITLE
Compatibilité Webpack

### ISSUE THREAD

**Issue by n-rodriguez** [lespoupeesrusses/promethee#28]
Bonjour!

Votre gem est trés intéressante : j'ai testé la démo et c'est vraiment génial :+1:

Malheureusement elle utilise sprockets et l'assets pipeline de Rails que je n'utilise plus depuis quelques mois au profit de Webpack et rails/webpacker pour gérer JS/CSS/images/fonts.

Avez vous prévu le support de Webpack via un module npm?

Merci!

**Comment by pabois** [comment]
Bonjour,

merci de votre retour, c'est toujours agréable ;-)
Pour le moment nous n'avons pas prévu de support de webpack. Peut-être en 2019 ?

Bien cordialement

**Comment by n-rodriguez** [comment]
>  Pour le moment nous n'avons pas prévu de support de webpack. Peut-être en 2019 ?

Vous voulez un coup de main?

**Comment by arnaudlevy** [comment]
Avec plaisir @n-rodriguez ! Merci beaucoup :)
